name: DiffDemo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.8.19
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - av==10.0.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - cachetools==5.3.1
      - certifi==2024.2.2
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - comm==0.1.3
      - compressai==1.2.6
      - contourpy==1.0.7
      - cycler==0.11.0
      - dahuffman==0.4.1
      - debugpy==1.6.7
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.9.2
      - defusedxml==0.7.1
      - einops==0.8.0
      - einx==0.2.2
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - filelock==3.12.0
      - fonttools==4.39.2
      - fqdn==1.5.1
      - frozendict==2.4.4
      - frozenlist==1.4.1
      - fsspec==2023.5.0
      - fvcore==0.1.5.post20221221
      - google-auth==2.21.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.0
      - h5py==3.8.0
      - hjson==3.1.0
      - huggingface-hub==0.14.1
      - idna==3.4
      - imageio==2.26.0
      - imageio-ffmpeg==0.4.8
      - imagesize==1.4.1
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - iopath==0.1.10
      - ipykernel==6.23.2
      - ipython==8.12.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.4.2
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lazy-loader==0.1
      - lpips==0.1.4
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - natsort==8.4.0
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.0
      - ninja==1.11.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numpy==1.24.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.7.0.72
      - packaging==23.0
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parameterized==0.9.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.5.3
      - portalocker==2.7.0
      - proglog==0.1.10
      - progressbar==2.5
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - protobuf==3.20.3
      - psutil==5.9.4
      - ptflops==0.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==1.10.9
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytorch-msssim==0.2.1
      - pytorchvideo==0.1.5
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.0.2
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rsa==4.9
      - safetensors==0.3.1
      - scikit-image==0.20.0
      - scikit-learn==1.3.2
      - scipy==1.9.1
      - seaborn==0.12.2
      - send2trash==1.8.2
      - six==1.16.0
      - sk-video==1.1.10
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.0
      - tensorboardx==2.6
      - termcolor==2.3.0
      - terminado==0.17.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2023.3.15
      - timm==0.9.2
      - tinycss2==1.2.1
      - torch==2.1.2
      - torch-geometric==2.5.3
      - torchvision==0.16.2
      - tornado==6.3.1
      - tqdm==4.65.0
      - traitlets==5.9.0
      - triton==2.1.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - uri-template==1.2.0
      - urllib3==1.26.16
      - vector-quantize-pytorch==1.14.8
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - werkzeug==2.3.6
      - widgetsnbextension==4.0.7
      - yacs==0.1.8
      - yarl==1.9.4
      - zipp==3.15.0
